import = [
"~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
family = "DankMono Nerd Font"
style = "Bold"

[font.italic]
family = "DankMono Nerd Font"
style = "Italic"

[font.normal]
family = "DankMono Nerd Font"
style = "Regular"

[window]
decorations = "buttonless"
opacity = 0.85

[window.padding]
x = 16
y = 16
