#!/usr/bin/env sh

limelight -m config width           2
limelight -m config radius          7
limelight -m config placement       inset
limelight -m config active_color    0x33ffffff
limelight -m config normal_color    0x33000000
