-- require("which-key").setup({
--     plugins = {
--         marks = true,
--         registers = true,
--         spelling = {
--             enabled = true,
--             suggestions = 20,
--         },
--     },
--     window = {
--         border = "none",
--         position = "bottom",
--         margin = { 1, 0, 1, 0 },
--         padding = { 1, 2, 1, 2 },
--     },
--     layout = {
--         height = { min = 4, max = 25 },
--         width = { min = 20, max = 50 },
--         spacing = 3,
--         align = "center",
--     },
-- })
